# Generated by Django 4.1.5 on 2023-01-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("image", models.FileField(blank=True, upload_to="idea/%Y%m%d")),
                ("description", models.TextField()),
                ("interest", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("kind", models.CharField(max_length=32)),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AddField(
            model_name="idea",
            name="devtool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idea_tool",
                to="posts.tool",
            ),
        ),
    ]
