# Generated by Django 4.1.5 on 2023-01-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_idea_tool_delete_user_idea_devtool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="devtool",
            field=models.CharField(
                choices=[
                    ("django", "Django"),
                    ("react", "React"),
                    ("java", "Java"),
                    ("c++", "C++"),
                    ("python", "Python"),
                ],
                max_length=52,
            ),
        ),
    ]
